package team_penguin.cs2450_project1;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author acer
 */
public class CreditScreen extends javax.swing.JFrame {

    /**
     * Creates new form CreditScreen
     */
    public CreditScreen() {
        initComponents();
        setSize(600,400);
        setLocation(300,200);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        credit_2 = new javax.swing.JLabel();
        credit_3 = new javax.swing.JLabel();
        credit_1 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        credit_4 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Credit");
        setResizable(false);
        getContentPane().setLayout(null);

        title.setFont(new java.awt.Font("Stencil", 1, 30)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Credit");
        getContentPane().add(title);
        title.setBounds(240, 30, 120, 60);

        credit_2.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        credit_2.setForeground(new java.awt.Color(255, 255, 255));
        credit_2.setText("Haowen Yin                   011781185");
        getContentPane().add(credit_2);
        credit_2.setBounds(90, 150, 440, 30);

        credit_3.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        credit_3.setForeground(new java.awt.Color(255, 255, 255));
        credit_3.setText("Amir Chaudhry           014897025 ");
        getContentPane().add(credit_3);
        credit_3.setBounds(90, 200, 440, 30);

        credit_1.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        credit_1.setForeground(new java.awt.Color(255, 255, 255));
        credit_1.setText("Beize Li                          014699412 ");
        getContentPane().add(credit_1);
        credit_1.setBounds(90, 100, 450, 30);

        backButton.setFont(new java.awt.Font("Stencil", 1, 28)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(50, 300, 120, 40);

        credit_4.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        credit_4.setForeground(new java.awt.Color(255, 255, 255));
        credit_4.setText("Auraiporn Auksorn  014068197");
        getContentPane().add(credit_4);
        credit_4.setBounds(90, 250, 440, 30);

        background.setBackground(new java.awt.Color(0, 51, 51));
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_penguin/cs2450_project1/credit and score.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(-1, 2, 600, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
         MenuScreen menuScreen = new MenuScreen();
         menuScreen.setVisible(true);
         dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CreditScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CreditScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CreditScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CreditScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new CreditScreen().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel background;
    private javax.swing.JLabel credit_1;
    private javax.swing.JLabel credit_2;
    private javax.swing.JLabel credit_3;
    private javax.swing.JLabel credit_4;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
