/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package team_penguin.cs2450_project1;

/**
 *
 * @author acer
 */

import java.util.Random;
import java.util.ArrayList;

public class Hangman extends javax.swing.JFrame {

    /**
     * Creates new form Hangman
     */
    
    public static String hangmanWord()
    {
        //Random number generator
        Random rand = new Random();
        // List of possible hangman words
        String[] words = {"abstract", "cemetery", "nurse", "pharmacy", "climbing"};
        // random select a position 
        return words[rand.nextInt(words.length)];
    }
    public static <T> void printAry(T[] ary)
    {
        for(int i = 0; i < ary.length; i++)
        {
            System.out.print(ary[i] + ", ");
        }
        System.out.print("\n");
    }
    public static void init(Integer[] ary)
    {
        for(int i = 0; i < ary.length; i++)
        {
            ary[i] = 0;
        }
    }
    public static Integer[] mark(Integer[] ary, ArrayList<Integer> position)
    {
        for(int i = 0; i < position.size(); i++)
        {
            ary[position.get(i)]=1;
        }
        return ary;
    }
    public static ArrayList<Integer> search(String word, char alphabet)
    {
        ArrayList<Integer> positions = new ArrayList<Integer>();
        for(int i = 0; i < word.length(); i++)
        {
            if(word.charAt(i) == alphabet)
            {
                positions.add(i);
            }
        }
        return positions;
    }
    public Hangman() {
        initComponents();
        
        //Select a word for guess
        //String word = hangmanWord();
        String word = "abstract";
        System.out.println(word);
        
        //Guess array
        Integer[] guess = new Integer[word.length()];
        //Initialize to 0
        init(guess);
        
        // Test mark
        mark(guess,search(word,'a'));
        
        //Testing print out
        printAry(guess);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        skipButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        skipButton.setText("Skip");
        skipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skipButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(skipButton)
                .addContainerGap(339, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(258, Short.MAX_VALUE)
                .addComponent(skipButton)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void skipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skipButtonActionPerformed
        // TODO add your handling code here:
        MainScreen ms = new MainScreen();
        ms.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_skipButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hangman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hangman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hangman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hangman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hangman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton skipButton;
    // End of variables declaration//GEN-END:variables
}
