/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package team_penguin.cs2450_project1;

import java.awt.event.ActionEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.BufferedWriter;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
/**
 *
 * @author amirc
 */
public class PlayerScore extends javax.swing.JFrame {

    /**
     * Creates new form PlayerScore
     */
    private int score_player; 
    private String playerName;
    
    private ArrayList<Integer> top_score_list;
    public PlayerScore(int score) {
        this();
        score_player = score;
        setScoreText();
        this.setVisible(true);
        checkHighScores();
    }
    
    public PlayerScore() {
        initComponents();
        setSize(600,400);
        setLocation(300,200);
        setResizable(false);
        keybindings();
        score_player = 110;
        top_score_list = new ArrayList<Integer>();
        setScoreText();
    }
    
    private void setScoreText()
    {
        Score.setText(Integer.toString(score_player));
    }

    private void checkHighScores()
    {
        try{
            //JOptionPane.showMessageDialog(null,System.getProperty("user.dir"));
            File myFile = new File("./src/main/java/team_penguin/cs2450_project1/score.txt");
            Scanner read = new Scanner(myFile);
            while(read.hasNextLine()){
                top_score_list.add(firstNumber(read.nextLine()));
            }
        }
        catch (FileNotFoundException e){
            JOptionPane.showMessageDialog(null, "File not found: score.txt");
        }
        
        int confirmation = 2;
        for(Integer score : top_score_list )
        {
            if(score_player > score)
            {
                confirmation = JOptionPane.showConfirmDialog(null,"You score is higher than the current top scores Do you want to be listed?", "Top Score Confirmation", JOptionPane.YES_NO_CANCEL_OPTION);
                break;
            }
        }
        if(confirmation == 0)
        {
            playerName = JOptionPane.showInputDialog("Please enter your name");
            if(playerName != null)
            {
                export();
            }
        }
    }
    
    private void export(){
        try{
            FileWriter fileWriter = new FileWriter("./src/main/java/team_penguin/cs2450_project1/score.txt",true);
            BufferedWriter bw = new BufferedWriter(fileWriter);
            bw.write(playerName + ": " + Integer.toString(score_player));
            bw.close();
            fileWriter.close();
        }
        catch(IOException e){
            JOptionPane.showMessageDialog(null, "Fail to write: score.txt");
        }
    }
    
    private Integer firstNumber(String s)
    {
        int i = 0;
        while(i < s.length() && s.charAt(i)!= ':')
        {
            i++;
        }
        while(i < s.length() && !Character.isDigit(s.charAt(i))){
            i++;
        }
        int j = i;
        while(j < s.length() && Character.isDigit(s.charAt(j)))
        {
            j++;
        }
        return Integer.parseInt(s.substring(i,j));
    }
            public void keybindings(){
        Action exit = new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                dispose();
                System.exit(0);
            }
        };
            String WindowClose = "exit";
            getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("ESCAPE"), WindowClose); 
            getRootPane().getActionMap().put(WindowClose, exit);
        Action dm = new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                    ProjectInfo dm = new ProjectInfo();
                    dm.setVisible(true);
                    dispose();
                }
            };
            String PopMenu = "dm";
            getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("F1"),PopMenu); 
            getRootPane().getActionMap().put(PopMenu,dm); 
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        End = new javax.swing.JButton();
        userscoreTitle = new javax.swing.JLabel();
        Score = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Player Score");
        getContentPane().setLayout(null);

        End.setFont(new java.awt.Font("Stencil", 1, 28)); // NOI18N
        End.setText("End");
        End.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EndActionPerformed(evt);
            }
        });
        getContentPane().add(End);
        End.setBounds(50, 270, 103, 37);

        userscoreTitle.setFont(new java.awt.Font("Stencil", 1, 30)); // NOI18N
        userscoreTitle.setForeground(new java.awt.Color(255, 255, 255));
        userscoreTitle.setText("Your Score");
        getContentPane().add(userscoreTitle);
        userscoreTitle.setBounds(197, 64, 260, 46);

        Score.setFont(new java.awt.Font("Stencil", 1, 40)); // NOI18N
        Score.setForeground(new java.awt.Color(255, 255, 255));
        Score.setText("100");
        getContentPane().add(Score);
        Score.setBounds(250, 120, 100, 80);

        Background.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_penguin/cs2450_project1/credit and score.jpg"))); // NOI18N
        Background.setText("100");
        getContentPane().add(Background);
        Background.setBounds(0, 0, 600, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EndActionPerformed
        // TODO add your handling code here:
        MenuScreen menuScreen = new MenuScreen();
         menuScreen.setVisible(true);
         dispose();
    }//GEN-LAST:event_EndActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PlayerScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PlayerScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PlayerScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PlayerScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PlayerScore().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton End;
    private javax.swing.JLabel Score;
    private javax.swing.JLabel userscoreTitle;
    // End of variables declaration//GEN-END:variables
}
