 package team_penguin.cs2450_project1;

import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Rectangle;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.KeyStroke;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


public class PongScreen extends javax.swing.JFrame {
    

    	
    public PongScreen() {
        
        initComponents();
        setSize(600,400);
        setLocation(300,200);
        setResizable(false);
        setTitle("Pong Game");
        showDate();
        showTime();
        jPanel1.add(new PongPanel());
        
       
        
        
    }
    
    void showDate(){
        Date d = new Date();
        SimpleDateFormat f = new SimpleDateFormat("MMMM dd, yyyy");
        Date.setText(f.format(d));
    }
    
    void showTime(){
        new Timer(0, new ActionListener(){
            
            @Override
            public void actionPerformed(ActionEvent e) {
               Date d = new Date();
               SimpleDateFormat f = new SimpleDateFormat("hh:mm:ss a");
               Time.setText(f.format(d));
            }
        }).start();
    }
    
    //Implementaion of esc key to exit program and f1 to pop out display. 
    public void keybindings(){
        Action exit = new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                dispose();
                System.exit(0);
            }
        };
            String WindowClose = "exit";
            getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("ESCAPE"), WindowClose); 
            getRootPane().getActionMap().put(WindowClose, exit);

        
            Action dm = new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                    ProjectInfo dm = new ProjectInfo();
                    dm.setVisible(true);
                    dispose();
                }
            };
            String PopMenu = "dm";
            getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("F1"),PopMenu); 
            getRootPane().getActionMap().put(PopMenu,dm);
            
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScoreA = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        Background = new javax.swing.JPanel();
        PlayerA = new javax.swing.JLabel();
        PlayerB = new javax.swing.JLabel();
        ScoreB = new javax.swing.JLabel();
        Quit = new javax.swing.JButton();
        jPanel1 = new PongPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        ScoreA.setFont(new java.awt.Font("Stencil", 3, 24)); // NOI18N
        ScoreA.setForeground(new java.awt.Color(51, 255, 51));
        ScoreA.setText("Score");
        ScoreA.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(153, 0, 153)));
        getContentPane().add(ScoreA);
        ScoreA.setBounds(16, 199, 90, 30);

        Time.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        Time.setText("Time");
        getContentPane().add(Time);
        Time.setBounds(436, 7, 142, 20);

        Date.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        Date.setText("Date");
        getContentPane().add(Date);
        Date.setBounds(285, 10, 144, 19);

        Title.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        Title.setForeground(new java.awt.Color(0, 153, 153));
        Title.setText("PONG");
        getContentPane().add(Title);
        Title.setBounds(29, 22, 70, 25);

        Background.setBackground(new java.awt.Color(255, 255, 255));

        PlayerA.setFont(new java.awt.Font("Stencil", 1, 25)); // NOI18N
        PlayerA.setForeground(new java.awt.Color(51, 255, 51));
        PlayerA.setText(" A");

        PlayerB.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        PlayerB.setForeground(new java.awt.Color(204, 0, 204));
        PlayerB.setText("B");

        ScoreB.setFont(new java.awt.Font("Stencil", 3, 24)); // NOI18N
        ScoreB.setForeground(new java.awt.Color(204, 0, 204));
        ScoreB.setText("Score");
        ScoreB.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(153, 0, 153)));

        Quit.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        Quit.setText("Quit");
        Quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(353, 310));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 353, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(PlayerA, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                        .addComponent(PlayerB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Quit)
                            .addComponent(ScoreB, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36))))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PlayerA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PlayerB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ScoreB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(Quit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        getContentPane().add(Background);
        Background.setBounds(0, 0, 600, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void QuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitActionPerformed
        dispose();
    }//GEN-LAST:event_QuitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PongScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PongScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PongScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PongScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PongScreen().setVisible(true);
            }
        });
       
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel Date;
    private javax.swing.JLabel PlayerA;
    private javax.swing.JLabel PlayerB;
    private javax.swing.JButton Quit;
    private javax.swing.JLabel ScoreA;
    private javax.swing.JLabel ScoreB;
    private javax.swing.JLabel Time;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
class PongPanel extends javax.swing.JPanel{
    Paddle paddle1 = new Paddle(30, 120, 1);
    Paddle paddle2 = new Paddle(310, 120, 2);
    Ball  ball  = new Ball(170, 150);
    Graphics g;
    
    @Override
    protected void paintComponent(Graphics g){
        super.paintComponent(g);
         paddle1.draw(g);
         paddle2.draw(g);
         ball.draw(g);
    }         

}

 class Ball { 
    int x, y, xDirection, yDirection;
    final int BALL_WIDTH = 15, BALL_HEIGHT = 15;
	
    public Ball(int x, int y){
	this.x = x;
	this.y = y;
    }
    public void setYDirection(int yDirection){
        this.yDirection = yDirection;
    }
    public void setXDirection(int xDirection){
        this.xDirection = xDirection;
    }
    public void draw(Graphics g){
         // to draw ball
        g.setColor(Color.WHITE);
        g.fillOval(this.x, this.y, BALL_WIDTH, BALL_HEIGHT);
    }

}

class Paddle {
    int x, y, yDirection, id;
    final int PADDLE_WIDTH = 10, PADDLE_HEIGHT = 60;
    Rectangle paddle;
    
    public Paddle(int x, int y, int id){
		this.x = x;
		this.y = y;
		this.id = id;
                paddle = new Rectangle(x,y,10,60);
    }
    
    public void setYDirection(int yDirection){
        this.yDirection = yDirection;
    }
		
    public void draw(Graphics g) {
		if(id==1){
                    //to draw left paddle
                    g.setColor(Color.green);
                    g.fillRect(paddle.x, paddle.y, PADDLE_WIDTH, PADDLE_HEIGHT);
                }
		if(id==2){
                    //to draw right paddle
                    g.setColor(Color.MAGENTA);
                    g.fillRect(paddle.x, paddle.y, PADDLE_WIDTH, PADDLE_HEIGHT);
                }
    }
	
}
