/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package team_penguin.cs2450_project1;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.Timer;
import javax.swing.WindowConstants;

/**
 *
 * @author Haowen Yin
 */
public class StartScreen extends javax.swing.JFrame  {
    
    /**
     * Creates new form StartScreen
     */
    public StartScreen() {
        initComponents();
        setSize(600,400);
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        TeamName = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hang Man Game");
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setName("StartFrame"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        Title.setFont(new java.awt.Font("Stencil", 1, 30)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("CS 2450 Hangman v.1.0");
        getContentPane().add(Title);
        Title.setBounds(100, 40, 410, 120);

        TeamName.setFont(new java.awt.Font("Stencil", 1, 28)); // NOI18N
        TeamName.setForeground(new java.awt.Color(255, 255, 255));
        TeamName.setText("By: Team Penguin");
        getContentPane().add(TeamName);
        TeamName.setBounds(150, 260, 290, 70);
        TeamName.getAccessibleContext().setAccessibleDescription("");

        //System.out.println(System.getProperty("java.class.path"));
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_penguin/cs2450_project1/final_bg.jpg"))); // NOI18N
        background.setPreferredSize(new java.awt.Dimension(610, 410));
        getContentPane().add(background);
        background.setBounds(0, 0, 610, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        StartScreen startScreen = new StartScreen();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            startScreen.setVisible(true);
            System.out.println(System.getProperty("getResources"));
          
        });
           
        // Set the startScreen appears for 3 sec and then use actionPerformed method to create a new activity (go to mainScreen)
        int delay = 3000; // 3000 miliseconds = 3 seconds
        ActionListener taskPerformer = new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                // Perform a task --> we want to go to a mainScreen 
                System.out.println("Already displayed for 3 sec, and going to a main screen now...");
                MenuScreen menuScreen = new MenuScreen();
                menuScreen.setVisible(true);
                startScreen.setVisible(false);
            }
        };
        Timer timer = new Timer(delay, taskPerformer);
        timer.setRepeats(false);
        timer.start();

        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TeamName;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel background;
    // End of variables declaration//GEN-END:variables

    
}
