/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package team_penguin.cs2450_project1;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import javax.swing.Timer;



/**
 *
 * @author amirc
 */
public class Sudoku extends javax.swing.JFrame {
    
    /**
     * Creates new form Sudoku
     */
    public Sudoku() {
        initComponents();
        setSize(600,400);
        setLocation(300,200);
        setResizable(false);  
        
        showDate();
        showTime();
        
        keybindings();
        
    }
    
    void showDate(){
        Date d = new Date();
        SimpleDateFormat f = new SimpleDateFormat("MMMM dd, yyyy");
        Date.setText(f.format(d));
    }
    
    void showTime(){
        new Timer(0, new ActionListener(){
            
            @Override
            public void actionPerformed(ActionEvent e) {
               Date d = new Date();
               SimpleDateFormat f = new SimpleDateFormat("hh:mm:ss a");
               Time.setText(f.format(d));
            }
        }).start();
    }
    
    //Implementaion of esc key to exit program and f1 to pop out display. 
    public void keybindings(){
    Action exit = new AbstractAction() {
        public void actionPerformed(ActionEvent e) {
        dispose();
        System.exit(0);
        Action dm = new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                    ProjectInfo dm = new ProjectInfo();
                    dm.setVisible(true);
                    dispose();
                }
            };
            String PopMenu = "dm";
            getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("F1"),PopMenu); 
            getRootPane().getActionMap().put(PopMenu,dm); 
    }
 };
        String WindowClose = "exit";
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("ESCAPE"), WindowClose); 
        getRootPane().getActionMap().put(WindowClose, exit);
        
    // I tried to implement f1 key but I don't know what I'm doing wrong n it does not do anything when f1 is pressed. 
        Action DisplayMenu = new AbstractAction() {
        public void actionPerformed(ActionEvent e) {
            ProjectInfo DisplayMenu = new ProjectInfo();
            DisplayMenu.setVisible(true);
            dispose();      
    }
 };
        String PopMenu = "DisplayMenu";
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("F1"),PopMenu); 
        getRootPane().getActionMap().put(PopMenu,DisplayMenu);
        
        
        
}
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")       
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GameBoard = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        b1 = new javax.swing.JTextField();
        b2 = new javax.swing.JTextField();
        b3 = new javax.swing.JTextField();
        b4 = new javax.swing.JTextField();
        b5 = new javax.swing.JTextField();
        b6 = new javax.swing.JTextField();
        b7 = new javax.swing.JTextField();
        b8 = new javax.swing.JTextField();
        b9 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        b10 = new javax.swing.JTextField();
        b11 = new javax.swing.JTextField();
        b12 = new javax.swing.JTextField();
        b13 = new javax.swing.JTextField();
        b14 = new javax.swing.JTextField();
        b15 = new javax.swing.JTextField();
        b16 = new javax.swing.JTextField();
        b17 = new javax.swing.JTextField();
        b18 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        b19 = new javax.swing.JTextField();
        b20 = new javax.swing.JTextField();
        b21 = new javax.swing.JTextField();
        b22 = new javax.swing.JTextField();
        b23 = new javax.swing.JTextField();
        b24 = new javax.swing.JTextField();
        b26 = new javax.swing.JTextField();
        b27 = new javax.swing.JTextField();
        b28 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        b29 = new javax.swing.JTextField();
        b30 = new javax.swing.JTextField();
        b31 = new javax.swing.JTextField();
        b32 = new javax.swing.JTextField();
        b33 = new javax.swing.JTextField();
        b34 = new javax.swing.JTextField();
        b35 = new javax.swing.JTextField();
        b36 = new javax.swing.JTextField();
        b37 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        b38 = new javax.swing.JTextField();
        b39 = new javax.swing.JTextField();
        b40 = new javax.swing.JTextField();
        b41 = new javax.swing.JTextField();
        b42 = new javax.swing.JTextField();
        b43 = new javax.swing.JTextField();
        b44 = new javax.swing.JTextField();
        b45 = new javax.swing.JTextField();
        b46 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        b48 = new javax.swing.JTextField();
        b49 = new javax.swing.JTextField();
        b50 = new javax.swing.JTextField();
        b51 = new javax.swing.JTextField();
        b52 = new javax.swing.JTextField();
        b54 = new javax.swing.JTextField();
        b55 = new javax.swing.JTextField();
        b56 = new javax.swing.JTextField();
        b57 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        b58 = new javax.swing.JTextField();
        b59 = new javax.swing.JTextField();
        b60 = new javax.swing.JTextField();
        b61 = new javax.swing.JTextField();
        b62 = new javax.swing.JTextField();
        b63 = new javax.swing.JTextField();
        b65 = new javax.swing.JTextField();
        b66 = new javax.swing.JTextField();
        b67 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        b68 = new javax.swing.JTextField();
        b69 = new javax.swing.JTextField();
        b70 = new javax.swing.JTextField();
        b71 = new javax.swing.JTextField();
        b72 = new javax.swing.JTextField();
        b73 = new javax.swing.JTextField();
        b74 = new javax.swing.JTextField();
        b75 = new javax.swing.JTextField();
        b76 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        b77 = new javax.swing.JTextField();
        b78 = new javax.swing.JTextField();
        b79 = new javax.swing.JTextField();
        b80 = new javax.swing.JTextField();
        b81 = new javax.swing.JTextField();
        b82 = new javax.swing.JTextField();
        b83 = new javax.swing.JTextField();
        b84 = new javax.swing.JTextField();
        b85 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Date = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GameBoard.setBackground(new java.awt.Color(255, 255, 255));
        GameBoard.setPreferredSize(new java.awt.Dimension(300, 300));
        GameBoard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setPreferredSize(new java.awt.Dimension(103, 103));

        b1.setEditable(false);
        b1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b1.setText("8");
        b1.setPreferredSize(new java.awt.Dimension(6, 47));
        b1.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b2.setPreferredSize(new java.awt.Dimension(6, 47));
        b2.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b3.setPreferredSize(new java.awt.Dimension(6, 47));
        b3.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b4.setPreferredSize(new java.awt.Dimension(6, 47));
        b4.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b5.setPreferredSize(new java.awt.Dimension(6, 47));
        b5.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b6.setPreferredSize(new java.awt.Dimension(6, 47));
        b6.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b7.setPreferredSize(new java.awt.Dimension(6, 47));
        b7.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b8.setEditable(false);
        b8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b8.setText("1");
        b8.setPreferredSize(new java.awt.Dimension(6, 47));
        b8.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b9.setPreferredSize(new java.awt.Dimension(6, 47));
        b9.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        GameBoard.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setPreferredSize(new java.awt.Dimension(103, 103));

        b10.setEditable(false);
        b10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b10.setText("5");
        b10.setPreferredSize(new java.awt.Dimension(6, 47));
        b10.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b11.setPreferredSize(new java.awt.Dimension(6, 47));
        b11.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b12.setEditable(false);
        b12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b12.setText("9");
        b12.setPreferredSize(new java.awt.Dimension(6, 47));
        b12.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b13.setPreferredSize(new java.awt.Dimension(6, 47));
        b13.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b14.setPreferredSize(new java.awt.Dimension(6, 47));
        b14.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b15.setPreferredSize(new java.awt.Dimension(6, 47));
        b15.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b16.setPreferredSize(new java.awt.Dimension(6, 47));
        b16.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b17.setEditable(false);
        b17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b17.setText("4");
        b17.setPreferredSize(new java.awt.Dimension(6, 47));
        b17.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b18.setEditable(false);
        b18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b18.setText("8");
        b18.setPreferredSize(new java.awt.Dimension(6, 47));
        b18.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(b16, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(b17, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(b13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(b14, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(b10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(b11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(b15, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b18, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b14, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b15, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b16, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b17, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b18, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        GameBoard.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.setPreferredSize(new java.awt.Dimension(103, 103));

        b19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b19.setPreferredSize(new java.awt.Dimension(6, 47));
        b19.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b20.setEditable(false);
        b20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b20.setText("5");
        b20.setPreferredSize(new java.awt.Dimension(6, 47));
        b20.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b21.setPreferredSize(new java.awt.Dimension(6, 47));
        b21.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b22.setPreferredSize(new java.awt.Dimension(6, 47));
        b22.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b23.setEditable(false);
        b23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b23.setText("3");
        b23.setPreferredSize(new java.awt.Dimension(6, 47));
        b23.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b24.setPreferredSize(new java.awt.Dimension(6, 47));
        b24.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b26.setEditable(false);
        b26.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b26.setText("2");
        b26.setPreferredSize(new java.awt.Dimension(6, 47));
        b26.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b27.setEditable(false);
        b27.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b27.setText("1");
        b27.setPreferredSize(new java.awt.Dimension(6, 47));
        b27.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b28.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b28.setPreferredSize(new java.awt.Dimension(6, 47));
        b28.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(b23, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b21, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b19, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(b20, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(b24, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(b22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b26, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b27, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b28, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b19, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b20, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b26, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b21, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b22, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b27, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b23, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b24, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b28, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        GameBoard.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel4.setPreferredSize(new java.awt.Dimension(103, 103));

        b29.setEditable(false);
        b29.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b29.setText("4");
        b29.setPreferredSize(new java.awt.Dimension(6, 47));
        b29.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b30.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b30.setPreferredSize(new java.awt.Dimension(6, 47));
        b30.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b31.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b31.setPreferredSize(new java.awt.Dimension(6, 47));
        b31.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b32.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b32.setPreferredSize(new java.awt.Dimension(6, 47));
        b32.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b33.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b33.setPreferredSize(new java.awt.Dimension(6, 47));
        b33.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b34.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b34.setPreferredSize(new java.awt.Dimension(6, 47));
        b34.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b35.setEditable(false);
        b35.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b35.setText("6");
        b35.setPreferredSize(new java.awt.Dimension(6, 47));
        b35.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b36.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b36.setPreferredSize(new java.awt.Dimension(6, 47));
        b36.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b37.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b37.setPreferredSize(new java.awt.Dimension(6, 47));
        b37.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(b33, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b31, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b29, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(b30, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(b35, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(b32, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(b36, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(b34, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(b37, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b29, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b30, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b35, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b31, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b32, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b36, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b33, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b34, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b37, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        GameBoard.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel5.setPreferredSize(new java.awt.Dimension(103, 103));

        b38.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b38.setPreferredSize(new java.awt.Dimension(6, 47));
        b38.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b39.setEditable(false);
        b39.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b39.setText("3");
        b39.setPreferredSize(new java.awt.Dimension(6, 47));
        b39.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b40.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b40.setPreferredSize(new java.awt.Dimension(6, 47));
        b40.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b41.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b41.setPreferredSize(new java.awt.Dimension(6, 47));
        b41.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b42.setEditable(false);
        b42.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b42.setText("7");
        b42.setPreferredSize(new java.awt.Dimension(6, 47));
        b42.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b43.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b43.setPreferredSize(new java.awt.Dimension(6, 47));
        b43.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b44.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b44.setPreferredSize(new java.awt.Dimension(6, 47));
        b44.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b45.setEditable(false);
        b45.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b45.setText("2");
        b45.setPreferredSize(new java.awt.Dimension(6, 47));
        b45.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b46.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b46.setPreferredSize(new java.awt.Dimension(6, 47));
        b46.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(b44, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b41, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b38, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(b39, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(b40, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b42, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b45, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b46, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b43, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b38, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b39, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b40, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b41, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b42, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b43, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b44, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b45, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b46, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        GameBoard.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel6.setPreferredSize(new java.awt.Dimension(103, 103));

        b48.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b48.setPreferredSize(new java.awt.Dimension(6, 47));
        b48.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b49.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b49.setPreferredSize(new java.awt.Dimension(6, 47));
        b49.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b50.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b50.setPreferredSize(new java.awt.Dimension(6, 47));
        b50.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b51.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b51.setPreferredSize(new java.awt.Dimension(6, 47));
        b51.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b52.setEditable(false);
        b52.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b52.setText("9");
        b52.setPreferredSize(new java.awt.Dimension(6, 47));
        b52.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b54.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b54.setPreferredSize(new java.awt.Dimension(6, 47));
        b54.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b55.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b55.setPreferredSize(new java.awt.Dimension(6, 47));
        b55.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b56.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b56.setPreferredSize(new java.awt.Dimension(6, 47));
        b56.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b57.setEditable(false);
        b57.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b57.setText("2");
        b57.setPreferredSize(new java.awt.Dimension(6, 47));
        b57.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(b52, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b50, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(b54, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(b57, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(b51, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(b56, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(b48, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(b49, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(b55, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b48, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b49, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b55, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b50, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b51, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b56, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b52, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b54, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b57, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        GameBoard.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel7.setMinimumSize(new java.awt.Dimension(104, 90));
        jPanel7.setPreferredSize(new java.awt.Dimension(103, 103));

        b58.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b58.setPreferredSize(new java.awt.Dimension(6, 47));
        b58.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b59.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b59.setPreferredSize(new java.awt.Dimension(6, 47));
        b59.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b60.setEditable(false);
        b60.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b60.setText("7");
        b60.setPreferredSize(new java.awt.Dimension(6, 47));
        b60.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b61.setEditable(false);
        b61.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b61.setText("4");
        b61.setPreferredSize(new java.awt.Dimension(6, 47));
        b61.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b62.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b62.setPreferredSize(new java.awt.Dimension(6, 47));
        b62.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b63.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b63.setPreferredSize(new java.awt.Dimension(6, 47));
        b63.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b65.setEditable(false);
        b65.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b65.setText("6");
        b65.setPreferredSize(new java.awt.Dimension(6, 47));
        b65.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b66.setEditable(false);
        b66.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b66.setText("5");
        b66.setPreferredSize(new java.awt.Dimension(6, 47));
        b66.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b67.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b67.setPreferredSize(new java.awt.Dimension(6, 47));
        b67.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(b58, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(b59, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(b60, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(b65, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(b66, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(b61, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(b62, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b63, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b67, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 1, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b58, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b59, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b60, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b61, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b62, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b63, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b65, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b66, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b67, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        GameBoard.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, -1));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel8.setPreferredSize(new java.awt.Dimension(103, 103));

        b68.setEditable(false);
        b68.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b68.setText("7");
        b68.setPreferredSize(new java.awt.Dimension(6, 47));
        b68.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b69.setEditable(false);
        b69.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b69.setText("8");
        b69.setPreferredSize(new java.awt.Dimension(6, 47));
        b69.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b70.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b70.setPreferredSize(new java.awt.Dimension(6, 47));
        b70.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b71.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b71.setPreferredSize(new java.awt.Dimension(6, 47));
        b71.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b72.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b72.setPreferredSize(new java.awt.Dimension(6, 47));
        b72.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b73.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b73.setPreferredSize(new java.awt.Dimension(6, 47));
        b73.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b74.setEditable(false);
        b74.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b74.setText("1");
        b74.setPreferredSize(new java.awt.Dimension(6, 47));
        b74.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b75.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b75.setPreferredSize(new java.awt.Dimension(6, 47));
        b75.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b76.setEditable(false);
        b76.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b76.setText("3");
        b76.setPreferredSize(new java.awt.Dimension(6, 47));
        b76.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(b68, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(b69, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(b71, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(b72, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(b70, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b73, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(b74, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(b75, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(b76, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b68, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b69, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b70, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b71, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b72, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b73, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b74, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b75, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b76, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        GameBoard.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel9.setPreferredSize(new java.awt.Dimension(103, 103));

        b77.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b77.setPreferredSize(new java.awt.Dimension(6, 47));
        b77.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b78.setEditable(false);
        b78.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b78.setText("9");
        b78.setPreferredSize(new java.awt.Dimension(6, 47));
        b78.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b79.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b79.setPreferredSize(new java.awt.Dimension(6, 47));
        b79.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b80.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b80.setPreferredSize(new java.awt.Dimension(6, 47));
        b80.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b81.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b81.setPreferredSize(new java.awt.Dimension(6, 47));
        b81.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b82.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b82.setPreferredSize(new java.awt.Dimension(6, 47));
        b82.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b83.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b83.setPreferredSize(new java.awt.Dimension(6, 47));
        b83.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b84.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b84.setPreferredSize(new java.awt.Dimension(6, 47));
        b84.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        b85.setEditable(false);
        b85.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b85.setText("5");
        b85.setPreferredSize(new java.awt.Dimension(6, 47));
        b85.setSelectedTextColor(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(b77, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(b78, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(b79, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(b83, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(b84, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(b80, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(b81, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b82, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b85, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b77, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b78, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b79, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b80, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b81, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b82, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b83, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b84, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b85, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        GameBoard.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        getContentPane().add(GameBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 303, 303));

        jButton1.setText("Submit");
        jButton1.setToolTipText("Submit to check out what you get");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 298, -1, -1));

        jButton2.setText("Quit");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 296, -1, -1));

        Date.setText("Date");
        getContentPane().add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 110, 23));

        Time.setText("Time");
        getContentPane().add(Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 97, 25));

        jLabel1.setFont(new java.awt.Font("Ravie", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Sudoku");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 100, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         ProjectInfo dm = new ProjectInfo();
         dm.setVisible(true);// TODO add your handling code here:
         dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sudoku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sudoku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sudoku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sudoku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sudoku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Date;
    private javax.swing.JPanel GameBoard;
    private javax.swing.JLabel Time;
    private javax.swing.JTextField b1;
    private javax.swing.JTextField b10;
    private javax.swing.JTextField b11;
    private javax.swing.JTextField b12;
    private javax.swing.JTextField b13;
    private javax.swing.JTextField b14;
    private javax.swing.JTextField b15;
    private javax.swing.JTextField b16;
    private javax.swing.JTextField b17;
    private javax.swing.JTextField b18;
    private javax.swing.JTextField b19;
    private javax.swing.JTextField b2;
    private javax.swing.JTextField b20;
    private javax.swing.JTextField b21;
    private javax.swing.JTextField b22;
    private javax.swing.JTextField b23;
    private javax.swing.JTextField b24;
    private javax.swing.JTextField b26;
    private javax.swing.JTextField b27;
    private javax.swing.JTextField b28;
    private javax.swing.JTextField b29;
    private javax.swing.JTextField b3;
    private javax.swing.JTextField b30;
    private javax.swing.JTextField b31;
    private javax.swing.JTextField b32;
    private javax.swing.JTextField b33;
    private javax.swing.JTextField b34;
    private javax.swing.JTextField b35;
    private javax.swing.JTextField b36;
    private javax.swing.JTextField b37;
    private javax.swing.JTextField b38;
    private javax.swing.JTextField b39;
    private javax.swing.JTextField b4;
    private javax.swing.JTextField b40;
    private javax.swing.JTextField b41;
    private javax.swing.JTextField b42;
    private javax.swing.JTextField b43;
    private javax.swing.JTextField b44;
    private javax.swing.JTextField b45;
    private javax.swing.JTextField b46;
    private javax.swing.JTextField b48;
    private javax.swing.JTextField b49;
    private javax.swing.JTextField b5;
    private javax.swing.JTextField b50;
    private javax.swing.JTextField b51;
    private javax.swing.JTextField b52;
    private javax.swing.JTextField b54;
    private javax.swing.JTextField b55;
    private javax.swing.JTextField b56;
    private javax.swing.JTextField b57;
    private javax.swing.JTextField b58;
    private javax.swing.JTextField b59;
    private javax.swing.JTextField b6;
    private javax.swing.JTextField b60;
    private javax.swing.JTextField b61;
    private javax.swing.JTextField b62;
    private javax.swing.JTextField b63;
    private javax.swing.JTextField b65;
    private javax.swing.JTextField b66;
    private javax.swing.JTextField b67;
    private javax.swing.JTextField b68;
    private javax.swing.JTextField b69;
    private javax.swing.JTextField b7;
    private javax.swing.JTextField b70;
    private javax.swing.JTextField b71;
    private javax.swing.JTextField b72;
    private javax.swing.JTextField b73;
    private javax.swing.JTextField b74;
    private javax.swing.JTextField b75;
    private javax.swing.JTextField b76;
    private javax.swing.JTextField b77;
    private javax.swing.JTextField b78;
    private javax.swing.JTextField b79;
    private javax.swing.JTextField b8;
    private javax.swing.JTextField b80;
    private javax.swing.JTextField b81;
    private javax.swing.JTextField b82;
    private javax.swing.JTextField b83;
    private javax.swing.JTextField b84;
    private javax.swing.JTextField b85;
    private javax.swing.JTextField b9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables

    


}
